name: Add New Subscriber v2

on:
  repository_dispatch:
    types: [new_subscription]

permissions:
  contents: write
  
jobs:
  add-subscriber:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUBTOKEN }}
          persist-credentials: true
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install Python dependencies
        run: |
          pip install google-generativeai python-dotenv reportlab
          
      - name: Add email to subscribers.json
        run: |
          python3 -c "
          import json
          import time
          
          # Load existing subscribers
          try:
              with open('dashboard/public/data/subscribers.json', 'r') as f:
                  subscribers = json.load(f)
          except FileNotFoundError:
              subscribers = []
          
          # Check if email already exists
          email = '${{ github.event.client_payload.email }}'
          if not any(sub['email'] == email for sub in subscribers):
              # Add new subscriber
              new_subscriber = {
                  'email': email,
                  'subscribed_at': '${{ github.event.client_payload.timestamp }}',
                  'active': True,
                  'id': int(time.time() * 1000)
              }
              subscribers.append(new_subscriber)
              
              # Save updated file
              with open('dashboard/public/data/subscribers.json', 'w') as f:
                  json.dump(subscribers, f, indent=2)
                  
              print(f'✅ Added new subscriber: {email}')
              
              # Mark as new subscriber for welcome email
              with open('new_subscriber_email.txt', 'w') as f:
                  f.write(email)
          else:
              print(f'📧 Email {email} already subscribed')
          "
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add changes if any
          git add dashboard/public/data/subscribers.json
          
          # Check if there are changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "🔔 Add new subscriber: ${{ github.event.client_payload.email }}"
            git push
            echo "✅ Subscriber added and committed"
          else
            echo "📧 No changes to commit (email may already exist)"
          fi
          
      - name: Send welcome email with current report
        if: hashFiles('new_subscriber_email.txt') != ''
        env:
          GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}
          GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: |
          if [ -f "new_subscriber_email.txt" ]; then
            NEW_EMAIL=$(cat new_subscriber_email.txt)
            echo "📧 Sending welcome email to: $NEW_EMAIL"
            
            # Send welcome email using Python script
            python3 send_welcome_email.py "$NEW_EMAIL"
            
            # Clean up
            rm -f new_subscriber_email.txt
          else
            echo "📧 No new subscriber to send welcome email to"
          fi